// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/hourglass/v1/customer.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on CustomerRegisterRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *CustomerRegisterRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for ProviderName

	return nil
}

// CustomerRegisterRequestValidationError is the validation error returned by
// CustomerRegisterRequest.Validate if the designated constraints aren't met.
type CustomerRegisterRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CustomerRegisterRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CustomerRegisterRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CustomerRegisterRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CustomerRegisterRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CustomerRegisterRequestValidationError) ErrorName() string {
	return "CustomerRegisterRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CustomerRegisterRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCustomerRegisterRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CustomerRegisterRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CustomerRegisterRequestValidationError{}

// Validate checks the field values on CustomerInfo with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *CustomerInfo) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for Quota

	// no validation rules for Weights

	return nil
}

// CustomerInfoValidationError is the validation error returned by
// CustomerInfo.Validate if the designated constraints aren't met.
type CustomerInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CustomerInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CustomerInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CustomerInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CustomerInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CustomerInfoValidationError) ErrorName() string { return "CustomerInfoValidationError" }

// Error satisfies the builtin error interface
func (e CustomerInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCustomerInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CustomerInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CustomerInfoValidationError{}

// Validate checks the field values on FeedbackRequest with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *FeedbackRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for Consume

	// no validation rules for ServiceName

	return nil
}

// FeedbackRequestValidationError is the validation error returned by
// FeedbackRequest.Validate if the designated constraints aren't met.
type FeedbackRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FeedbackRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FeedbackRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FeedbackRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FeedbackRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FeedbackRequestValidationError) ErrorName() string { return "FeedbackRequestValidationError" }

// Error satisfies the builtin error interface
func (e FeedbackRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFeedbackRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FeedbackRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FeedbackRequestValidationError{}
